/*** Automatically generated by genlibdefs.awk. Do not edit ***/
#ifndef _LIBDEFS_H
#define _LIBDEFS_H
#define NAME_STRING      "autodoc.datatype"
#define NT_TYPE          NT_LIBRARY
#define NOLIBHEADER
#define LC_BUILDNAME(n)  n
#define LIBBASE          AutodocBase
#define LIBBASETYPE      struct AutodocBase_intern
#define LIBBASETYPEPTR   struct AutodocBase_intern *
#define VERSION_NUMBER   1
#define REVISION_NUMBER  0
#define BASENAME         autodoc
#define BASENAME_STRING  "autodoc"
#define VERSION_STRING   "$VER: autodoc 1.0 (14.09.26)\r\n"
#define LIBEND           autodoc_end
#define LIBFUNCTABLE     autodoc_functable
#define COPYRIGHT_STRING ""
#endif /* _LIBDEFS_H */